// <auto-generated />
namespace chat_exjobb_v3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class slug : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(slug));
        
        string IMigrationMetadata.Id
        {
            get { return "201605080954211_slug"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
